name: Build and Release

on:
  push:
      branches:
        - master
  workflow_dispatch:
    inputs:
      api_base_url:
        description: "Set the API Base URL"
        required: true
        default: "http://localhost:8080"
        
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Version
        id: set_version
        run: |
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set Environment Variables for Manual Run
        if: github.event_name == 'workflow_dispatch'
        run: |
          sed -i 's|VITE_API_BASE_URL=.*|VITE_API_BASE_URL=${{ github.event.inputs.api_base_url }}|g' .env
          
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Package as ZIP
        run: |
          mkdir -p release
          cp -r dist/* release/
          zip -r release${{ env.VERSION }}.zip release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release${{ env.VERSION }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifact
          path: dist/

      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          tag_name: v${{ needs.build.outputs.version }}
          name: "Release v${{ needs.build.outputs.version }}"
          body: "Automated release from GitHub Actions"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Test Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          tag_name: "v${{ needs.build.outputs.version }}-${{ github.run_number }}"
          name: "Test release v${{ needs.build.outputs.version }}-${{ github.run_number }}"
          body: "Automated release from GitHub Actions"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
