name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      api_base_url:
        description: "Set the API Base URL"
        required: true
        default: "http://localhost:8080"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set Environment Variables for Manual Run
        if: github.event_name == 'workflow_dispatch'
        run: |
          sed -i 's|VITE_API_BASE_URL=.*|VITE_API_BASE_URL=${{ github.event.inputs.api_base_url }}|g' .env
          
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Package as ZIP
        run: |
          mkdir -p release
          cp -r dist/* release/
          zip -r release${{ github.run_number }}.zip release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release${{ github.run_number }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/** 
          tag_name: v1.0.${{ github.run_number }}  # Auto-increment tag
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "Automated release from GitHub Actions"
          draft: false
          prerelease: false
